[project]
name = "model-testing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["ollama", "fastapi", "uvicorn", "pydantic"]

[dependency-groups]
dev = [
    "isort>=6.0.1",
]
