# jenkins.yaml
jenkins:
  systemMessage: "Jenkins configured with Configuration as Code for Kubernetes deployment."
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "${ADMIN_PASSWORD}"

  # Configure Kubernetes cloud
  clouds:
    - kubernetes:
        name: "kubernetes"
        serverUrl: "https://kubernetes.default.svc.cluster.local"
        namespace: "default"
        credentialsId: "k8s-service-account"
        jenkinsUrl: "http://jenkins-service:8080"
        jenkinsTunnel: "jenkins-service:50000"
        connectTimeout: 5
        readTimeout: 15
        maxRequestsPerHost: 32
        retentionTimeout: 5

        templates:
          - name: "jenkins-agent"
            namespace: "default"
            nodeUsageMode: NORMAL
            label: "jenkins-agent"
            containers:
              - name: "jnlp"
                image: "jenkins/inbound-agent:latest"
                workingDir: "/home/jenkins/agent"
                command: ""
                args: ""
                ttyEnabled: true
                resourceRequestCpu: "100m"
                resourceRequestMemory: "256Mi"
                resourceLimitCpu: "500m"
                resourceLimitMemory: "512Mi"
              - name: "docker"
                image: "docker:dind"
                workingDir: "/home/jenkins/agent"
                command: ""
                args: ""
                ttyEnabled: true
                privileged: true
                resourceRequestCpu: "100m"
                resourceRequestMemory: "256Mi"
                resourceLimitCpu: "1000m"
                resourceLimitMemory: "1Gi"

# Global tool configuration
tool:
  git:
    installations:
      - name: "Default"
        home: "git"

# Credentials configuration (will be mounted as secrets)
credentials:
  system:
    domainCredentials:
      - credentials:
          - kubernetesServiceAccount:
              scope: GLOBAL
              id: "k8s-service-account"
              description: "Kubernetes service account for Jenkins"
