FROM python:3.13-slim

RUN curl -LsSf https://astral.sh/uv/install.sh | sh

# Add the UV binary directory to the PATH
ENV PATH="/var/jenkins_home/.local/bin:${PATH}"

# Install FastAPI and Ollama
RUN pip install fastapi ollama uvicorn[standard]
# Copy the main.py file into the container
COPY main.py /app/main.py

WORKDIR /app
# Expose the port FastAPI will run on
EXPOSE 8000
# Command to run the FastAPI application using Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
